<script setup>
import {
  Activity,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  AudioLines,
  Bell,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleX,
  Clock3,
  Copy,
  CreditCard,
  Crown,
  Database,
  EllipsisVertical,
  ExternalLink,
  FileText,
  Folder,
  Globe,
  House,
  KeyRound,
  Laptop,
  LockKeyhole,
  Mail,
  Menu,
  Network,
  Pencil,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Trash2,
  TriangleAlert,
  Upload,
  Users,
  Video,
  X,
  Cpu,
} from "@lucide/vue";
defineProps({
  name: { type: String, default: "chart" },
  size: { type: [Number, String], default: 19 },
});
const icons = {
  activity: Activity,
  download: ArrowDownToLine,
  back: ArrowLeft,
  arrow: ArrowRight,
  audio: AudioLines,
  bell: Bell,
  building: Building2,
  calendar: CalendarDays,
  chart: ChartNoAxesCombined,
  check: Check,
  checks: CheckCheck,
  down: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  success: CircleCheck,
  failure: CircleX,
  clock: Clock3,
  copy: Copy,
  credit: CreditCard,
  crown: Crown,
  database: Database,
  more: EllipsisVertical,
  external: ExternalLink,
  file: FileText,
  folder: Folder,
  globe: Globe,
  home: House,
  key: KeyRound,
  laptop: Laptop,
  lock: LockKeyhole,
  mail: Mail,
  menu: Menu,
  network: Network,
  edit: Pencil,
  plus: Plus,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  phone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  trash: Trash2,
  alert: TriangleAlert,
  upload: Upload,
  users: Users,
  video: Video,
  x: X,
  cpu: Cpu,
};
</script>
<template>
  <component
    :is="icons[name] || icons.chart"
    :size="size"
    :stroke-width="1.7"
    aria-hidden="true"
  />
</template>
