import { reactive } from "vue";

export const defaults = {
  name: "Ruinion AI",
  description:
    "Plateforme de transcription et de résumés de réunions pour les équipes.",
  url: "https://ruinionai.example",
  language: "Français",
  timezone: "Africa/Abidjan (GMT+0)",
  dateFormat: "JJ/MM/AAAA",
  timeFormat: "24 heures",
  currency: "XOF (FCFA)",
  transcription: true,
  summary: true,
  documents: true,
  teams: true,
  integrations: true,
  publicApi: false,
  audioModel: "Voxtral Mini",
  summaryModel: "Mistral Large",
  exportFormat: "Word (.docx)",
  template: "Structure professionnelle",
  diarization: true,
  removeSilence: true,
  translation: false,
  twoFactor: true,
  google: true,
  microsoft: false,
  inviteLinks: true,
  sessionDuration: "30 jours",
  passwordPolicy: "Standard",
  emailNotifications: true,
  securityAlerts: true,
  weeklyReport: false,
  retention: "18 mois",
  autoDelete: "Après 18 mois",
  keepOriginal: true,
  compress: true,
  paymentMethod: "Virement bancaire",
  invoicePrefix: "RUI",
  paymentDelay: "30 jours",
  vat: 18,
  langfuse: true,
  googleMeet: false,
  teamsIntegration: false,
  accent: "Violet",
  density: "Confortable",
};
export const demoSettings = reactive({ ...defaults });
