"""initial saas schema

Revision ID: 1d6cb7a4a9b8
Revises: 
Create Date: 2026-09-07 18:38:51.902792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6cb7a4a9b8'
down_revision: Union[str, Sequence[str], None] = "0c4a1b2d3e4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'member', name='organization_member_role'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.add_column('meetings', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('meetings', sa.Column('summary_short', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('summary_long', sa.Text(), nullable=True))
    op.execute("UPDATE meetings SET summary_long = summary WHERE summary IS NOT NULL")
    op.add_column('meetings', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('meetings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('meetings', 'participants',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key('fk_meetings_organization_id_organizations', 'meetings', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_meetings_created_by_user_id_users', 'meetings', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('meetings', 'summary')
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('meetings', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.execute("UPDATE meetings SET summary = summary_long WHERE summary_long IS NOT NULL")
    op.drop_constraint('fk_meetings_created_by_user_id_users', 'meetings', type_='foreignkey')
    op.drop_constraint('fk_meetings_organization_id_organizations', 'meetings', type_='foreignkey')
    op.alter_column('meetings', 'participants',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('meetings', 'updated_at')
    op.drop_column('meetings', 'created_at')
    op.drop_column('meetings', 'created_by_user_id')
    op.drop_column('meetings', 'summary_long')
    op.drop_column('meetings', 'summary_short')
    op.drop_column('meetings', 'organization_id')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
