"""add team management

Revision ID: ebea4dc47b12
Revises: 9a8b7c6d5e4f
Create Date: 2026-09-22 03:32:34.182613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebea4dc47b12'
down_revision: Union[str, Sequence[str], None] = '9a8b7c6d5e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "ALTER TYPE organization_member_role "
        "ADD VALUE IF NOT EXISTS 'owner' BEFORE 'admin'"
    )

    postgresql.ENUM(
        "active",
        "inactive",
        name="organization_member_status",
    ).create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='organization_invitation_role'), server_default='member', nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'revoked', name='organization_invitation_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_id'), 'organization_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token_hash'), 'organization_invitations', ['token_hash'], unique=True)
    op.alter_column('meetings', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('organization_members', sa.Column('status', sa.Enum('active', 'inactive', name='organization_member_status'), server_default='active', nullable=False))
    op.alter_column('organization_members', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(
        "organization_members",
        "role",
        existing_type=postgresql.ENUM(
            "owner", "admin", "member",
            name="organization_member_role",
        ),
        nullable=False,
        server_default="member",
    )
    op.create_unique_constraint('uq_organization_members_organization_user', 'organization_members', ['organization_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM organization_members
                WHERE role::text = 'owner'
            ) OR EXISTS (
                SELECT 1 FROM organization_invitations
            ) THEN
                RAISE EXCEPTION
                    'Retour arriere bloque : owner ou invitations existants.';
            END IF;
        END;
        $$
    """)

    op.drop_constraint(
        "uq_organization_members_organization_user",
        "organization_members",
        type_="unique",
    )

    op.alter_column(
        "organization_members",
        "role",
        nullable=True,
        server_default=None,
    )

    for column in ("organization_id", "user_id"):
        op.alter_column(
            "organization_members", column, nullable=True
        )

    op.drop_column("organization_members", "status")
    op.alter_column("meetings", "organization_id", nullable=True)

    # Les index de la table sont aussi supprimes.
    op.drop_table("organization_invitations")

    for enum_name in (
        "organization_member_status",
        "organization_invitation_role",
        "organization_invitation_status",
    ):
        postgresql.ENUM(name=enum_name).drop(
            op.get_bind(), checkfirst=True
        )

    op.execute("""
        CREATE TYPE organization_member_role_previous
        AS ENUM ('admin', 'member')
    """)

    op.execute("""
        ALTER TABLE organization_members
            ALTER COLUMN role TYPE organization_member_role_previous
            USING role::text::organization_member_role_previous
    """)

    op.execute("DROP TYPE organization_member_role")

    op.execute("""
        ALTER TYPE organization_member_role_previous
        RENAME TO organization_member_role
    """)
